// <auto-generated />
namespace Assignment4_ALI_K_MOHAMAD.N.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Initial2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005151152007_Initial2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
